[profile.default]
solc = "0.8.26"
auto_detect_solc = false
bytecode_hash = "none"
optimizer_runs = 0
optimizer = true

sparse_mode = true

src = 'src'
via_ir = true
ffi = true
fs_permissions = [
  { access = "read", path = "./script" },
  { access = "write", path = "./deployments" }
]
verbosity = 3
evm_version = "cancun"
gas_limit = "300000000"

out = 'out'
test = 'test/'
cache_path = 'cache/foundry'

libs = ["lib"]

remappings = [
  # forge-std tests
  "ds-test/=lib/forge-std/lib/ds-test/",

  # OpenZeppelin - single source of truth (nested v4-core copy)
  "@openzeppelin/=lib/doppler/lib/v4-core/lib/openzeppelin-contracts/contracts/",
  "openzeppelin-contracts/=lib/doppler/lib/v4-core/lib/openzeppelin-contracts/contracts/",
]

# Specify include paths to control which directories are searched for imports
include_paths = [
  "src",
  "lib/forge-std/src"
]

ignored_paths = [
  # Ignore the top-level OZ copy to ensure only one version is compiled
  "lib/openzeppelin-contracts"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
unichainSepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100
