[profile.default]
auto_detect_solc = true
src = 'src'
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = "read", path = "./script" }]
verbosity = 3
evm_version = "cancun"
gas_limit = "300000000"
bytecode_hash = "none"
out = 'out'
test = 'test/'
cache_path = 'cache/foundry'

libs = ["lib"]

remappings = [
  # forge-std tests
  "ds-test/=lib/forge-std/lib/ds-test/",

  # Doppler helpers - main doppler remapping
  "doppler/=lib/doppler/",

  # OpenZeppelin Contracts v5 (standard)
  "@openzeppelin/=lib/doppler/lib/v4-core/lib/openzeppelin-contracts/contracts/",

  # OpenZeppelin Contracts Upgradeable
  "@openzeppelin/contracts-upgradeable/=lib/doppler/lib/v4-core/lib/openzeppelin-contracts-upgradeable/contracts/",
]

# Specify include paths to control which directories are searched for imports
include_paths = [
  "src",
  "lib/doppler/src",
  "lib/doppler/lib/v4-core/lib/openzeppelin-contracts/contracts",
  "lib/forge-std/src"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
unichainSepolia = "https://unichain-sepolia.g.alchemy.com/v2/USgCyvEGfIfHHcEq0bRvG-QDnmUZQEoS"
baseSepolia = "https://base-sepolia.g.alchemy.com/v2/-yMhiIdfJzvNodml7B9IcI673We9SxjM"

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100
